version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: lavanderiababycare
      MYSQL_ROOT_PASSWORD: 9310
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    environment:
      SPRING_APPLICATION_NAME: lavanderiababycare
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/lavanderiababycare
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 9310
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

volumes:
  db_data:
